'use client'

import { useState, useRef, useMemo } from 'react'
import { PageBreadcrumb } from '@/components/PageBreadcrumb'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Input } from '@/components/ui/input'
import type { HappyPathStep, Assumption, Dimension } from '@/lib/pm-toolkit-types'
import { DIMENSIONS, DIMENSION_COLORS } from '@/lib/pm-toolkit-types'

type Stage = 'input' | 'loading-happy-path' | 'happy-path-review' | 'loading-assumptions' | 'complete'
type ApiError = 'demo_limit_reached' | 'invalid_password' | 'input_too_short' | 'quota_exceeded' | 'server_error' | null

interface PasswordModal { open: boolean; error: boolean; loading: boolean }

async function callApi<T>(
  action: string,
  body: Record<string, unknown>,
  demoPassword?: string
): Promise<{ data?: T; error?: ApiError }> {
  try {
    const res = await fetch('/api/pm-toolkit', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action, ...body, ...(demoPassword ? { demoPassword } : {}) }),
    })
    const json = await res.json()
    if (!res.ok) return { error: json.error ?? 'server_error' }
    return { data: json }
  } catch {
    return { error: 'server_error' }
  }
}

function generateMarkdown(
  inputMode: 'simple' | 'detailed',
  inputText: string,
  happyPath: HappyPathStep[],
  assumptions: Assumption[]
): string {
  const lines: string[] = ['# Assumption Map', '_Generated by nickomori.com/projects/pm-toolkit_', '']

  lines.push('## Happy Path', '')
  if (inputMode === 'simple' && happyPath.length > 0) {
    lines.push('| Step | Actor | Action |', '|------|-------|--------|')
    for (const s of happyPath) lines.push(`| ${s.step} | ${s.actor} | ${s.action} |`)
  } else {
    lines.push(inputText)
  }
  lines.push('')

  lines.push('## Assumptions by Dimension', '')
  for (const dim of DIMENSIONS) {
    const group = assumptions.filter(a => a.dimension === dim)
    if (group.length === 0) continue
    lines.push(`### ${dim}`, '')
    lines.push('| # | Assumption | Importance | Confidence |', '|---|-----------|:---:|:---:|')
    group.forEach((a, i) => lines.push(`| ${i + 1} | ${a.text} | ${a.importance} | ${a.confidence} |`))
    lines.push('')
  }

  const sorted = [...assumptions].sort((a, b) =>
    b.importance * (10 - b.confidence) - a.importance * (10 - a.confidence)
  )
  lines.push('## Priority Matrix (sorted: importance × low-confidence)', '')
  lines.push('| Label | Dimension | Assumption | Importance | Confidence |', '|-------|-----------|-----------|:---:|:---:|')
  for (const a of sorted) {
    lines.push(`| ${a.label} | ${a.dimension} | ${a.text} | ${a.importance} | ${a.confidence} |`)
  }

  return lines.join('\n')
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function importanceLabel(score: number): { text: string; cls: string } {
  if (score >= 8) return { text: 'Critical', cls: 'text-destructive' }
  if (score >= 6) return { text: 'High', cls: 'text-warning' }
  if (score >= 4) return { text: 'Medium', cls: 'text-muted-foreground' }
  return { text: 'Low', cls: 'text-foreground-subtle' }
}

function confidenceLabel(score: number): { text: string; cls: string } {
  if (score >= 8) return { text: 'Confident', cls: 'text-success' }
  if (score >= 6) return { text: 'Somewhat confident', cls: 'text-muted-foreground' }
  if (score >= 4) return { text: 'Uncertain', cls: 'text-warning' }
  return { text: 'Low confidence', cls: 'text-destructive' }
}

function postItOffset(id: string): { x: number; y: number } {
  let h = 0
  for (const c of id) h = (h * 31 + c.charCodeAt(0)) | 0
  return { x: (Math.abs(h) % 20) - 10, y: (Math.abs(h * 13) % 20) - 10 }
}

// ─── Actor lane styles ───────────────────────────────────────────────────────

const ACTOR_LANE: Record<string, { dot: string; label: string; rowBg: string; stepBg: string; stepBorder: string }> = {
  'User':                  { dot: 'bg-blue-400',    label: 'text-blue-300',    rowBg: 'bg-blue-950/25',    stepBg: 'bg-blue-950/60',    stepBorder: 'border-blue-800/70' },
  'Platform':              { dot: 'bg-slate-400',   label: 'text-slate-300',   rowBg: 'bg-slate-900/30',   stepBg: 'bg-slate-800/50',   stepBorder: 'border-slate-700/70' },
  'Other User':            { dot: 'bg-emerald-400', label: 'text-emerald-300', rowBg: 'bg-emerald-950/25', stepBg: 'bg-emerald-950/60', stepBorder: 'border-emerald-800/70' },
  'Third-Party Service':   { dot: 'bg-purple-400',  label: 'text-purple-300',  rowBg: 'bg-purple-950/25',  stepBg: 'bg-purple-950/60',  stepBorder: 'border-purple-800/70' },
  'Admin':                 { dot: 'bg-amber-400',   label: 'text-amber-300',   rowBg: 'bg-amber-950/25',   stepBg: 'bg-amber-950/60',   stepBorder: 'border-amber-800/70' },
}
const DEFAULT_ACTOR = { dot: 'bg-muted-foreground', label: 'text-muted-foreground', rowBg: 'bg-card', stepBg: 'bg-secondary', stepBorder: 'border-border' }

// ─── Post-it colors for matrix ───────────────────────────────────────────────

const POSTIT: Record<Dimension, { bg: string; text: string }> = {
  'Desirability':   { bg: '#312e81', text: '#c7d2fe' },
  'Feasibility':    { bg: '#4c1d95', text: '#ddd6fe' },
  'Usability':      { bg: '#064e3b', text: '#a7f3d0' },
  'Viability':      { bg: '#78350f', text: '#fde68a' },
  'Ethical/Legal':  { bg: '#7f1d1d', text: '#fecaca' },
}

// ─── Main export ─────────────────────────────────────────────────────────────

export function PMToolkitClient() {
  const [stage, setStage] = useState<Stage>('input')
  const [inputMode, setInputMode] = useState<'simple' | 'detailed'>('simple')
  const [inputText, setInputText] = useState('')
  const [happyPath, setHappyPath] = useState<HappyPathStep[]>([])
  const [assumptions, setAssumptions] = useState<Assumption[]>([])
  const [error, setError] = useState<string | null>(null)
  const [modal, setModal] = useState<PasswordModal>({ open: false, error: false, loading: false })
  const [passwordInput, setPasswordInput] = useState('')
  const pendingWithPassword = useRef<((pw: string) => void) | null>(null)

  function openPasswordModal(retry: (pw: string) => void) {
    pendingWithPassword.current = retry
    setModal({ open: true, error: false, loading: false })
  }

  async function submitPassword() {
    if (!passwordInput || !pendingWithPassword.current) return
    setModal(m => ({ ...m, loading: true, error: false }))
    pendingWithPassword.current(passwordInput)
  }

  async function generateHappyPath(demoPassword?: string) {
    setStage('loading-happy-path')
    setError(null)
    const result = await callApi<{ steps: HappyPathStep[] }>('generate-happy-path', { input: inputText }, demoPassword)
    if (result.error === 'demo_limit_reached') { setStage('input'); openPasswordModal(pw => void generateHappyPath(pw)); return }
    if (result.error === 'invalid_password') { setModal(m => ({ ...m, loading: false, error: true })); setStage('input'); return }
    if (result.error === 'quota_exceeded') { setError('The AI service is temporarily unavailable. Please try again later.'); setStage('input'); return }
    if (result.error) { setError('Something went wrong. Please try again.'); setStage('input'); return }
    setModal({ open: false, error: false, loading: false })
    setPasswordInput('')
    setHappyPath(result.data!.steps)
    setStage('happy-path-review')
  }

  async function generateAssumptions(demoPassword?: string) {
    setStage('loading-assumptions')
    setError(null)
    const happyPathText = inputMode === 'detailed'
      ? inputText
      : happyPath.map(s => `Step ${s.step} (${s.actor}): ${s.action}`).join('\n')
    const result = await callApi<{ assumptions: Assumption[] }>('generate-assumptions', { happyPath: happyPathText }, demoPassword)
    const fallbackStage = inputMode === 'detailed' ? 'input' : 'happy-path-review'
    if (result.error === 'demo_limit_reached') { setStage(fallbackStage); openPasswordModal(pw => void generateAssumptions(pw)); return }
    if (result.error === 'invalid_password') { setModal(m => ({ ...m, loading: false, error: true })); setStage(fallbackStage); return }
    if (result.error === 'quota_exceeded') { setError('The AI service is temporarily unavailable. Please try again later.'); setStage(fallbackStage); return }
    if (result.error) { setError('Something went wrong. Please try again.'); setStage(fallbackStage); return }
    setModal({ open: false, error: false, loading: false })
    setPasswordInput('')
    setAssumptions(result.data!.assumptions)
    setStage('complete')
  }

  function handleExportMarkdown() {
    const content = generateMarkdown(inputMode, inputText, happyPath, assumptions)
    const blob = new Blob([content], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'assumption-map.md'
    a.click()
    URL.revokeObjectURL(url)
  }

  function handleReset() {
    setStage('input'); setInputText(''); setHappyPath([]); setAssumptions([]); setError(null)
  }

  return (
    <main className="min-h-screen bg-background px-6 py-10">
      <div className="max-w-5xl mx-auto">
        <PageBreadcrumb crumbs={[
          { label: 'Constructive Distractions', href: '/projects' },
          { label: 'Assumption Mapper' },
        ]} />

        <div className="mb-10">
          <p className="text-xs text-muted-foreground uppercase tracking-widest mb-4">Constructive Distractions</p>
          <h1 className="text-4xl font-bold text-foreground tracking-tight mb-4 font-heading">Assumption Mapper</h1>
          <p className="text-base text-foreground mb-3 max-w-2xl leading-relaxed">
            Describe a product idea or feature. Get swim lanes, a full assumption map across the five{' '}
            <a href="https://www.producttalk.org/continuous-discovery-habits/" target="_blank" rel="noopener noreferrer"
              className="underline underline-offset-2 hover:text-foreground transition-colors">
              Teresa Torres
            </a>{' '}
            dimensions, and a priority matrix — instantly.
          </p>
          <blockquote className="border-l-2 border-border pl-3">
            <p className="text-sm text-muted-foreground italic leading-relaxed">
              &ldquo;The faster we make our ideas tangible, the sooner we will be able to evaluate them, refine them, and zero in on the best solution.&rdquo;
            </p>
            <p className="text-xs text-muted-foreground mt-1">— Tim Brown, <span className="not-italic">Change by Design</span></p>
          </blockquote>
        </div>

        {error && (
          <div className="mb-6 rounded-lg border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>
        )}

        {stage === 'input' && (
          <InputStep inputMode={inputMode} inputText={inputText} onModeChange={setInputMode}
            onTextChange={setInputText}
            onSubmit={() => { if (inputMode === 'simple') void generateHappyPath(); else void generateAssumptions() }} />
        )}
        {(stage === 'loading-happy-path' || stage === 'loading-assumptions') && <LoadingState stage={stage} />}
        {stage === 'happy-path-review' && (
          <HappyPathReview steps={happyPath} onContinue={() => void generateAssumptions()} onReset={handleReset} />
        )}
        {stage === 'complete' && (
          <CompleteView inputMode={inputMode} inputText={inputText} happyPath={happyPath}
            assumptions={assumptions} onExport={handleExportMarkdown} onReset={handleReset} />
        )}
      </div>

      {modal.open && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 px-6">
          <div className="w-full max-w-sm rounded-xl border border-border bg-surface-overlay p-6 shadow-2xl">
            <h2 className="text-base font-semibold text-foreground mb-1">Demo access required</h2>
            <p className="text-sm text-muted-foreground mb-4">
              Enter the demo code from Nick&apos;s resume or LinkedIn to continue.
            </p>
            <Input type="password" placeholder="Demo code" value={passwordInput}
              onChange={e => setPasswordInput(e.target.value)}
              onKeyDown={e => { if (e.key === 'Enter') void submitPassword() }}
              className="mb-3" autoFocus />
            {modal.error && <p className="text-xs text-destructive mb-3">Incorrect code. Try again.</p>}
            <div className="flex gap-2">
              <Button onClick={() => void submitPassword()} disabled={!passwordInput || modal.loading} className="flex-1">
                {modal.loading ? 'Verifying…' : 'Continue'}
              </Button>
              <Button variant="outline" onClick={() => { setModal({ open: false, error: false, loading: false }); setPasswordInput('') }}>
                Cancel
              </Button>
            </div>
          </div>
        </div>
      )}
    </main>
  )
}

// ─── Input step ──────────────────────────────────────────────────────────────

function InputStep({
  inputMode, inputText, onModeChange, onTextChange, onSubmit,
}: {
  inputMode: 'simple' | 'detailed'
  inputText: string
  onModeChange: (mode: 'simple' | 'detailed') => void
  onTextChange: (text: string) => void
  onSubmit: () => void
}) {
  const simplePlaceholder = `Describe your product idea in a sentence or two. The AI will map out the happy path and then generate the assumption map.

Example: "A filter-sharing feature in our B2B analytics tool where a PM saves their current dashboard filters and shares them with teammates. A teammate opens the link, sees the dashboard pre-filtered, and can save or modify their own copy."`

  const detailedPlaceholder = `Describe the full happy path yourself — walk through each step by actor.

Example:
Step 1 (User): Opens the analytics dashboard and applies a set of filters.
Step 2 (User): Clicks "Save & Share" and names the filter set.
Step 3 (Platform): Generates a shareable link and copies it to clipboard.
Step 4 (Other User): Opens the link and is prompted to load the filters.
Step 5 (Platform): Applies the filters to the recipient's dashboard view.
Step 6 (Other User): Saves a personal copy of the filter set.`

  return (
    <div className="space-y-4">
      <div className="flex gap-2">
        {(['simple', 'detailed'] as const).map(mode => (
          <button key={mode} onClick={() => onModeChange(mode)}
            className={`text-sm px-3 py-1.5 rounded-lg border transition-colors ${
              inputMode === mode
                ? 'border-foreground text-foreground bg-secondary'
                : 'border-border text-muted-foreground hover:border-border-hover hover:text-foreground'
            }`}>
            {mode === 'simple' ? 'I have an idea' : "I'll describe the happy path"}
          </button>
        ))}
      </div>
      <Textarea value={inputText} onChange={e => onTextChange(e.target.value)}
        placeholder={inputMode === 'simple' ? simplePlaceholder : detailedPlaceholder}
        className="min-h-[180px] resize-none text-sm leading-relaxed" />
      <div className="flex items-center justify-between">
        <p className="text-xs text-muted-foreground">
          {inputMode === 'simple'
            ? 'The AI will generate the happy path first, then map assumptions.'
            : 'Describing the full path produces sharper, more specific assumptions.'}
        </p>
        <Button onClick={onSubmit} disabled={inputText.trim().length < 10}>
          {inputMode === 'simple' ? 'Map it →' : 'Generate assumptions →'}
        </Button>
      </div>
    </div>
  )
}

// ─── Loading ─────────────────────────────────────────────────────────────────

function LoadingState({ stage }: { stage: Stage }) {
  return (
    <div className="flex flex-col items-center justify-center py-20 gap-4">
      <div className="h-6 w-6 rounded-full border-2 border-border border-t-foreground animate-spin" />
      <p className="text-sm text-muted-foreground">
        {stage === 'loading-happy-path' ? 'Mapping the happy path…' : 'Generating assumptions across all five dimensions…'}
      </p>
    </div>
  )
}

// ─── Swim lane view ───────────────────────────────────────────────────────────

function SwimLaneView({ steps }: { steps: HappyPathStep[] }) {
  const actors = [...new Set(steps.map(s => s.actor))]
  const maxStep = steps.length > 0 ? Math.max(...steps.map(s => s.step)) : 0
  if (maxStep === 0) return null

  return (
    <div className="overflow-x-auto rounded-lg border border-border">
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: `112px repeat(${maxStep}, minmax(148px, 1fr))`,
          minWidth: `${112 + maxStep * 148}px`,
        }}
      >
        {actors.flatMap((actor, actorIdx) => {
          const actorSteps = steps.filter(s => s.actor === actor)
          const c = ACTOR_LANE[actor] ?? DEFAULT_ACTOR
          const isLastRow = actorIdx === actors.length - 1

          return [
            <div
              key={`label-${actor}`}
              className={`flex items-center gap-2.5 px-4 border-r border-border ${c.rowBg} ${!isLastRow ? 'border-b border-border' : ''}`}
              style={{ gridColumn: 1, gridRow: actorIdx + 1, minHeight: 96 }}
            >
              <div className={`w-2 h-2 rounded-full flex-shrink-0 ${c.dot}`} />
              <span className={`text-xs font-semibold leading-tight ${c.label}`}>{actor}</span>
            </div>,

            ...Array.from({ length: maxStep }, (_, i) => {
              const stepNum = i + 1
              const step = actorSteps.find(s => s.step === stepNum)
              const isLastCol = stepNum === maxStep

              return (
                <div
                  key={`${actor}-${stepNum}`}
                  className={`relative flex items-center p-3 ${c.rowBg} ${!isLastRow ? 'border-b border-border' : ''} ${!isLastCol ? 'border-r border-border' : ''}`}
                  style={{ gridColumn: stepNum + 1, gridRow: actorIdx + 1, minHeight: 96 }}
                >
                  {/* Lane connector line */}
                  <div className={`absolute top-1/2 left-0 right-0 h-px pointer-events-none ${c.stepBorder} opacity-40`} />

                  {step && (
                    <div className={`relative z-10 ${c.stepBg} border ${c.stepBorder} rounded-md px-3 py-2.5 w-full shadow-sm`}>
                      <span className="text-[9px] text-muted-foreground font-mono mb-1.5 block">{step.step}</span>
                      <p className="text-sm text-foreground leading-snug">{step.action}</p>
                    </div>
                  )}
                </div>
              )
            }),
          ]
        })}
      </div>
    </div>
  )
}

// ─── Happy path review ────────────────────────────────────────────────────────

function HappyPathReview({ steps, onContinue, onReset }: {
  steps: HappyPathStep[]
  onContinue: () => void
  onReset: () => void
}) {
  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-base font-semibold text-foreground mb-1">Happy Path</h2>
        <p className="text-sm text-muted-foreground">
          Review the swim lanes. If something looks off, start over with a more detailed description.
        </p>
      </div>
      <SwimLaneView steps={steps} />
      <div className="flex items-center gap-3">
        <Button onClick={onContinue}>Generate assumption map →</Button>
        <button onClick={onReset} className="text-sm text-muted-foreground hover:text-foreground transition-colors">
          Start over
        </button>
      </div>
    </div>
  )
}

// ─── Complete view ────────────────────────────────────────────────────────────

function CompleteView({ inputMode, inputText, happyPath, assumptions, onExport, onReset }: {
  inputMode: 'simple' | 'detailed'
  inputText: string
  happyPath: HappyPathStep[]
  assumptions: Assumption[]
  onExport: () => void
  onReset: () => void
}) {
  const [swimLanesOpen, setSwimLanesOpen] = useState(false)

  return (
    <div className="space-y-10">
      {/* Swim lanes — collapsed by default */}
      <section>
        <button onClick={() => setSwimLanesOpen(o => !o)}
          className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors mb-3">
          <span className="text-xs">{swimLanesOpen ? '▼' : '▶'}</span>
          Happy Path
        </button>
        {swimLanesOpen && (
          inputMode === 'simple' && happyPath.length > 0
            ? <SwimLaneView steps={happyPath} />
            : <pre className="text-sm text-muted-foreground whitespace-pre-wrap font-mono leading-relaxed rounded-lg border border-border bg-card px-4 py-3">{inputText}</pre>
        )}
      </section>

      {/* Priority Matrix */}
      <section>
        <h2 className="text-base font-semibold text-foreground mb-1">Priority Matrix</h2>
        <p className="text-xs text-muted-foreground mb-4">
          Top-right = high importance, low confidence — these need validation first. Hover any note for the full assumption.
        </p>
        <PriorityMatrix assumptions={assumptions} />
        <div className="flex flex-wrap gap-3 mt-4">
          {DIMENSIONS.map(dim => (
            <div key={dim} className="flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-sm inline-block" style={{ backgroundColor: POSTIT[dim].bg, outline: `1px solid ${POSTIT[dim].text}30` }} />
              <span className="text-xs text-muted-foreground">{dim}</span>
            </div>
          ))}
        </div>
      </section>

      {/* Assumption Map */}
      <section>
        <h2 className="text-base font-semibold text-foreground mb-4">Assumption Map</h2>
        <div className="space-y-6">
          {DIMENSIONS.map(dim => {
            const group = assumptions.filter(a => a.dimension === dim).sort((a, b) => b.importance - a.importance)
            if (group.length === 0) return null
            const c = DIMENSION_COLORS[dim]
            return (
              <div key={dim}>
                <div className="flex items-center gap-2 mb-2">
                  <span className="w-2 h-2 rounded-full flex-shrink-0" style={{ backgroundColor: c.dot }} />
                  <h3 className="text-sm font-medium text-foreground">{dim}</h3>
                  <span className="text-xs text-muted-foreground">({group.length})</span>
                </div>
                <div className="rounded-lg border border-border overflow-hidden">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-border bg-card/50">
                        <th className="text-left text-[10px] text-muted-foreground font-normal px-4 py-2">Assumption</th>
                        <th className="text-right text-[10px] text-muted-foreground font-normal px-3 py-2 w-24 whitespace-nowrap">Importance</th>
                        <th className="text-right text-[10px] text-muted-foreground font-normal px-4 py-2 w-32 whitespace-nowrap">Confidence</th>
                      </tr>
                    </thead>
                    <tbody>
                      {group.map((a, rowIdx) => {
                        const imp = importanceLabel(a.importance)
                        const conf = confidenceLabel(a.confidence)
                        return (
                          <tr key={a.id} className={`border-b border-border/50 last:border-b-0 ${rowIdx % 2 === 0 ? 'bg-card' : 'bg-background'}`}>
                            <td className="px-4 py-3 text-foreground leading-relaxed">{a.text}</td>
                            <td className="px-3 py-3 text-right">
                              <span className={`text-[10px] font-medium ${imp.cls}`}>{imp.text}</span>
                            </td>
                            <td className="px-4 py-3 text-right">
                              <span className={`text-[10px] ${conf.cls}`}>{conf.text}</span>
                            </td>
                          </tr>
                        )
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
            )
          })}
        </div>
      </section>

      {/* Actions */}
      <section className="flex items-center gap-4 pb-10">
        <Button onClick={onExport} variant="outline">Export as Markdown</Button>
        <button onClick={onReset} className="text-sm text-muted-foreground hover:text-foreground transition-colors">
          Start over
        </button>
      </section>
    </div>
  )
}

// ─── Priority matrix ──────────────────────────────────────────────────────────

function PriorityMatrix({ assumptions }: { assumptions: Assumption[] }) {
  const [hovered, setHovered] = useState<string | null>(null)

  const topToValidate = [...assumptions]
    .sort((a, b) => b.importance * (10 - b.confidence) - a.importance * (10 - a.confidence))
    .slice(0, 7)

  // Spread items that share the same score so they don't fully overlap
  const groupOffsets = useMemo(() => {
    const map = new Map<string, { x: number; y: number }>()
    const groups = new Map<string, Assumption[]>()
    for (const a of assumptions) {
      const key = `${a.importance}-${a.confidence}`
      if (!groups.has(key)) groups.set(key, [])
      groups.get(key)!.push(a)
    }
    for (const group of groups.values()) {
      const n = group.length
      group.forEach((a, i) => {
        if (n === 1) { map.set(a.id, { x: 0, y: 0 }); return }
        const spread = Math.min(n * 16, 56)
        map.set(a.id, {
          x: -spread / 2 + i * (spread / (n - 1)),
          y: (i % 2 === 0 ? 0 : -10),
        })
      })
    }
    return map
  }, [assumptions])

  return (
    <div className="space-y-6">
      {/* 2x2 matrix */}
      <div className="flex gap-3">
        {/* Y-axis label */}
        <div className="flex items-center">
          <div className="text-[10px] text-muted-foreground whitespace-nowrap"
            style={{ writingMode: 'vertical-rl', transform: 'rotate(180deg)' }}>
            ↑ Importance
          </div>
        </div>

        <div className="flex-1 relative" style={{ paddingTop: '60%' }}>
          <div className="absolute inset-0 rounded-lg border border-border bg-card overflow-visible">
            {/* Top-right highlight */}
            <div className="absolute top-0 right-0 w-1/2 h-1/2 bg-amber-500/8 rounded-tr-lg" />
            {/* Center lines */}
            <div className="absolute top-1/2 left-0 right-0 h-px bg-border" />
            <div className="absolute left-1/2 top-0 bottom-0 w-px bg-border" />
            {/* Quadrant label */}
            <div className="absolute top-2 right-3 text-[9px] text-amber-400/60 font-semibold tracking-wider uppercase">
              Validate First
            </div>

            {/* Post-it notes */}
            {assumptions.map(a => {
              const xPct = (10 - a.confidence) / 9 * 88 + 6
              const yPct = (10 - a.importance) / 9 * 88 + 6
              const off = groupOffsets.get(a.id) ?? { x: 0, y: 0 }
              const p = POSTIT[a.dimension]
              const isHovered = hovered === a.id

              return (
                <div
                  key={a.id}
                  className="absolute cursor-default"
                  style={{
                    left: `${xPct}%`,
                    top: `${yPct}%`,
                    transform: `translate(calc(-50% + ${off.x}px), calc(-50% + ${off.y}px))`,
                    zIndex: isHovered ? 60 : 10,
                  }}
                  onMouseEnter={() => setHovered(a.id)}
                  onMouseLeave={() => setHovered(null)}
                >
                  {/* Post-it square */}
                  <div
                    className="flex items-center justify-center p-2 rounded-sm transition-all duration-150"
                    style={{
                      width: 64,
                      height: 64,
                      backgroundColor: isHovered ? p.bg : `${p.bg}55`,
                      border: `1.5px solid ${p.text}30`,
                      transform: isHovered ? 'scale(1.15)' : 'scale(1)',
                      boxShadow: isHovered
                        ? `0 8px 20px rgba(0,0,0,0.6), 0 0 0 1px ${p.text}40`
                        : '0 2px 6px rgba(0,0,0,0.35)',
                      opacity: isHovered ? 1 : 0.75,
                    }}
                  >
                    <p
                      className="text-[9px] font-medium leading-tight text-center line-clamp-3"
                      style={{ color: isHovered ? p.text : `${p.text}cc` }}
                    >
                      {a.label}
                    </p>
                  </div>

                  {/* Hover tooltip */}
                  {isHovered && (
                    <div
                      className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-56 bg-surface-overlay border border-border rounded-lg p-3 shadow-2xl pointer-events-none"
                      style={{ zIndex: 100 }}
                    >
                      <p className="text-xs text-foreground leading-relaxed mb-2">{a.text}</p>
                      <div className="flex items-center justify-between">
                        <span className="text-[9px] font-medium" style={{ color: p.text }}>{a.dimension}</span>
                        <div className="flex flex-col items-end gap-0.5">
                          <span className={`text-[9px] font-medium ${importanceLabel(a.importance).cls}`}>
                            {importanceLabel(a.importance).text}
                          </span>
                          <span className={`text-[9px] ${confidenceLabel(a.confidence).cls}`}>
                            {confidenceLabel(a.confidence).text}
                          </span>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        </div>
      </div>

      {/* X-axis label */}
      <div className="flex justify-between text-[10px] text-muted-foreground ml-7 pr-1">
        <span>← High Confidence</span>
        <span>Low Confidence →</span>
      </div>

      {/* Top items to validate */}
      <div>
        <h3 className="text-sm font-medium text-foreground mb-3">Top assumptions to validate first</h3>
        <div className="space-y-1.5">
          {topToValidate.map((a, i) => {
            const p = POSTIT[a.dimension]
            const imp = importanceLabel(a.importance)
            const conf = confidenceLabel(a.confidence)
            return (
              <div key={a.id} className="flex items-start gap-3 rounded-lg border border-border bg-card px-4 py-2.5">
                <span className="text-xs text-muted-foreground font-mono mt-0.5 w-4 flex-shrink-0">{i + 1}</span>
                <div className="w-1.5 h-1.5 rounded-sm mt-1.5 flex-shrink-0" style={{ backgroundColor: p.bg, outline: `1px solid ${p.text}50` }} />
                <p className="text-sm text-foreground flex-1 leading-relaxed">{a.text}</p>
                <div className="flex flex-col items-end gap-0.5 flex-shrink-0 pt-0.5 min-w-[100px]">
                  <span className={`text-[10px] font-medium ${imp.cls}`}>{imp.text}</span>
                  <span className={`text-[10px] ${conf.cls}`}>{conf.text}</span>
                </div>
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}
