'use client'

import { useState, useRef } from 'react'
import { PageBreadcrumb } from '@/components/PageBreadcrumb'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Input } from '@/components/ui/input'
import type { HappyPathStep, Assumption, Dimension } from '@/lib/pm-toolkit-types'
import { DIMENSIONS, DIMENSION_COLORS } from '@/lib/pm-toolkit-types'

type Stage = 'input' | 'loading-happy-path' | 'happy-path-review' | 'loading-assumptions' | 'complete'
type ApiError = 'demo_limit_reached' | 'invalid_password' | 'input_too_short' | 'quota_exceeded' | 'server_error' | null

interface PasswordModal {
  open: boolean
  error: boolean
  loading: boolean
}

async function callApi<T>(
  action: string,
  body: Record<string, unknown>,
  demoPassword?: string
): Promise<{ data?: T; error?: ApiError }> {
  try {
    const res = await fetch('/api/pm-toolkit', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action, ...body, ...(demoPassword ? { demoPassword } : {}) }),
    })
    const json = await res.json()
    if (!res.ok) return { error: json.error ?? 'server_error' }
    return { data: json }
  } catch {
    return { error: 'server_error' }
  }
}

function generateMarkdown(
  inputMode: 'simple' | 'detailed',
  inputText: string,
  happyPath: HappyPathStep[],
  assumptions: Assumption[]
): string {
  const lines: string[] = ['# Assumption Map', '_Generated by nickomori.com/portfolio/pm-toolkit_', '']

  lines.push('## Happy Path', '')
  if (inputMode === 'simple' && happyPath.length > 0) {
    lines.push('| Step | Actor | Action |', '|------|-------|--------|')
    for (const s of happyPath) {
      lines.push(`| ${s.step} | ${s.actor} | ${s.action} |`)
    }
  } else {
    lines.push(inputText)
  }
  lines.push('')

  lines.push('## Assumptions by Dimension', '')
  for (const dim of DIMENSIONS) {
    const group = assumptions.filter(a => a.dimension === dim)
    if (group.length === 0) continue
    lines.push(`### ${dim}`, '')
    lines.push('| # | Assumption | Importance | Confidence |', '|---|-----------|:---:|:---:|')
    group.forEach((a, i) => {
      lines.push(`| ${i + 1} | ${a.text} | ${a.importance} | ${a.confidence} |`)
    })
    lines.push('')
  }

  const sorted = [...assumptions].sort((a, b) => {
    const priorityA = a.importance * (10 - a.confidence)
    const priorityB = b.importance * (10 - b.confidence)
    return priorityB - priorityA
  })

  lines.push('## Priority Matrix (sorted by importance × low-confidence)', '')
  lines.push('| Label | Dimension | Assumption | Importance | Confidence |', '|-------|-----------|-----------|:---:|:---:|')
  for (const a of sorted) {
    lines.push(`| ${a.label} | ${a.dimension} | ${a.text} | ${a.importance} | ${a.confidence} |`)
  }

  return lines.join('\n')
}

export function PMToolkitClient() {
  const [stage, setStage] = useState<Stage>('input')
  const [inputMode, setInputMode] = useState<'simple' | 'detailed'>('simple')
  const [inputText, setInputText] = useState('')
  const [happyPath, setHappyPath] = useState<HappyPathStep[]>([])
  const [assumptions, setAssumptions] = useState<Assumption[]>([])
  const [error, setError] = useState<string | null>(null)
  const [modal, setModal] = useState<PasswordModal>({ open: false, error: false, loading: false })
  const [passwordInput, setPasswordInput] = useState('')
  const pendingWithPassword = useRef<((pw: string) => void) | null>(null)

  function openPasswordModal(retry: (pw: string) => void) {
    pendingWithPassword.current = retry
    setModal({ open: true, error: false, loading: false })
  }

  async function submitPassword() {
    if (!passwordInput || !pendingWithPassword.current) return
    setModal(m => ({ ...m, loading: true, error: false }))
    pendingWithPassword.current(passwordInput)
  }

  async function generateHappyPath(demoPassword?: string) {
    setStage('loading-happy-path')
    setError(null)

    const result = await callApi<{ steps: HappyPathStep[] }>(
      'generate-happy-path',
      { input: inputText },
      demoPassword
    )

    if (result.error === 'demo_limit_reached') {
      setStage('input')
      openPasswordModal((pw) => void generateHappyPath(pw))
      return
    }
    if (result.error === 'invalid_password') {
      setModal(m => ({ ...m, loading: false, error: true }))
      setStage('input')
      return
    }
    if (result.error === 'quota_exceeded') {
      setError('The AI service is temporarily unavailable. Please try again later.')
      setStage('input')
      return
    }
    if (result.error) {
      setError('Something went wrong. Please try again.')
      setStage('input')
      return
    }

    setModal({ open: false, error: false, loading: false })
    setPasswordInput('')
    setHappyPath(result.data!.steps)
    setStage('happy-path-review')
  }

  async function generateAssumptions(demoPassword?: string) {
    setStage('loading-assumptions')
    setError(null)

    const happyPathText = inputMode === 'detailed'
      ? inputText
      : happyPath.map(s => `Step ${s.step} (${s.actor}): ${s.action}`).join('\n')

    const result = await callApi<{ assumptions: Assumption[] }>(
      'generate-assumptions',
      { happyPath: happyPathText },
      demoPassword
    )

    if (result.error === 'demo_limit_reached') {
      setStage(inputMode === 'detailed' ? 'input' : 'happy-path-review')
      openPasswordModal((pw) => void generateAssumptions(pw))
      return
    }
    if (result.error === 'invalid_password') {
      setModal(m => ({ ...m, loading: false, error: true }))
      setStage(inputMode === 'detailed' ? 'input' : 'happy-path-review')
      return
    }
    if (result.error === 'quota_exceeded') {
      setError('The AI service is temporarily unavailable. Please try again later.')
      setStage(inputMode === 'detailed' ? 'input' : 'happy-path-review')
      return
    }
    if (result.error) {
      setError('Something went wrong. Please try again.')
      setStage(inputMode === 'detailed' ? 'input' : 'happy-path-review')
      return
    }

    setModal({ open: false, error: false, loading: false })
    setPasswordInput('')
    setAssumptions(result.data!.assumptions)
    setStage('complete')
  }

  function handleExportMarkdown() {
    const content = generateMarkdown(inputMode, inputText, happyPath, assumptions)
    const blob = new Blob([content], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'assumption-map.md'
    a.click()
    URL.revokeObjectURL(url)
  }

  function handleReset() {
    setStage('input')
    setInputText('')
    setHappyPath([])
    setAssumptions([])
    setError(null)
  }

  return (
    <main className="min-h-screen bg-background px-6 py-10">
      <div className="max-w-4xl mx-auto">
        <PageBreadcrumb crumbs={[
          { label: 'Constructive Distractions', href: '/portfolio' },
          { label: 'Assumption Mapper' },
        ]} />

        <div className="mb-8">
          <h1 className="text-2xl font-semibold text-foreground mb-2">Assumption Mapper</h1>
          <p className="text-sm text-muted-foreground max-w-2xl leading-relaxed">
            Describe a product idea or feature. Get swim lanes, a full assumption map across the five{' '}
            <a
              href="https://www.producttalk.org/continuous-discovery-habits/"
              target="_blank"
              rel="noopener noreferrer"
              className="underline underline-offset-2 hover:text-foreground transition-colors"
            >
              Teresa Torres
            </a>{' '}
            dimensions, and a priority matrix — instantly. Built on the{' '}
            <a
              href="https://dschool.stanford.edu/resources/design-thinking-bootleg"
              target="_blank"
              rel="noopener noreferrer"
              className="underline underline-offset-2 hover:text-foreground transition-colors"
            >
              Stanford d.school
            </a>{' '}
            principle that 0→1 is the hard part.
          </p>
        </div>

        {error && (
          <div className="mb-6 rounded-lg border border-red-800 bg-red-950/30 px-4 py-3 text-sm text-red-300">
            {error}
          </div>
        )}

        {stage === 'input' && (
          <InputStep
            inputMode={inputMode}
            inputText={inputText}
            onModeChange={setInputMode}
            onTextChange={setInputText}
            onSubmit={() => {
              if (inputMode === 'simple') void generateHappyPath()
              else void generateAssumptions()
            }}
          />
        )}

        {(stage === 'loading-happy-path' || stage === 'loading-assumptions') && (
          <LoadingState stage={stage} />
        )}

        {stage === 'happy-path-review' && (
          <HappyPathReview
            steps={happyPath}
            onContinue={() => void generateAssumptions()}
            onReset={handleReset}
          />
        )}

        {stage === 'complete' && (
          <CompleteView
            inputMode={inputMode}
            inputText={inputText}
            happyPath={happyPath}
            assumptions={assumptions}
            onExport={handleExportMarkdown}
            onReset={handleReset}
          />
        )}
      </div>

      {modal.open && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 px-6">
          <div className="w-full max-w-sm rounded-xl border border-border bg-card p-6 shadow-2xl">
            <h2 className="text-base font-semibold text-white mb-1">Demo access required</h2>
            <p className="text-sm text-neutral-400 mb-4">
              Enter the demo code from Nick&apos;s resume or LinkedIn to continue.
            </p>
            <Input
              type="password"
              placeholder="Demo code"
              value={passwordInput}
              onChange={e => setPasswordInput(e.target.value)}
              onKeyDown={e => { if (e.key === 'Enter') void submitPassword() }}
              className="mb-3"
              autoFocus
            />
            {modal.error && (
              <p className="text-xs text-red-400 mb-3">Incorrect code. Try again.</p>
            )}
            <div className="flex gap-2">
              <Button
                onClick={() => void submitPassword()}
                disabled={!passwordInput || modal.loading}
                className="flex-1"
              >
                {modal.loading ? 'Verifying…' : 'Continue'}
              </Button>
              <Button
                variant="outline"
                onClick={() => {
                  setModal({ open: false, error: false, loading: false })
                  setPasswordInput('')
                }}
              >
                Cancel
              </Button>
            </div>
          </div>
        </div>
      )}
    </main>
  )
}

function InputStep({
  inputMode,
  inputText,
  onModeChange,
  onTextChange,
  onSubmit,
}: {
  inputMode: 'simple' | 'detailed'
  inputText: string
  onModeChange: (mode: 'simple' | 'detailed') => void
  onTextChange: (text: string) => void
  onSubmit: () => void
}) {
  const simpleplaceholder = `Describe your product idea in a sentence or two. The AI will map out the happy path and then generate the assumption map.

Example: "A filter-sharing feature in our B2B analytics tool where a PM saves their current dashboard filters and shares them with teammates. A teammate opens the link, sees the dashboard pre-filtered, and can save or modify their own copy."`

  const detailedPlaceholder = `Describe the full happy path yourself — walk through each step by actor.

Example:
Step 1 (User): Opens the analytics dashboard and applies a set of filters.
Step 2 (User): Clicks "Save & Share" and names the filter set.
Step 3 (Platform): Generates a shareable link and copies it to clipboard.
Step 4 (Other User): Opens the link and is prompted to load the filters.
Step 5 (Platform): Applies the filters to the recipient's dashboard view.
Step 6 (Other User): Saves a personal copy of the filter set.`

  return (
    <div className="space-y-4">
      <div className="flex gap-2">
        <button
          onClick={() => onModeChange('simple')}
          className={`text-sm px-3 py-1.5 rounded-lg border transition-colors ${
            inputMode === 'simple'
              ? 'border-neutral-500 text-foreground bg-secondary'
              : 'border-border text-muted-foreground hover:border-neutral-500 hover:text-foreground'
          }`}
        >
          I have an idea
        </button>
        <button
          onClick={() => onModeChange('detailed')}
          className={`text-sm px-3 py-1.5 rounded-lg border transition-colors ${
            inputMode === 'detailed'
              ? 'border-neutral-500 text-foreground bg-secondary'
              : 'border-border text-muted-foreground hover:border-neutral-500 hover:text-foreground'
          }`}
        >
          I&apos;ll describe the happy path
        </button>
      </div>

      <Textarea
        value={inputText}
        onChange={e => onTextChange(e.target.value)}
        placeholder={inputMode === 'simple' ? simpleplaceholder : detailedPlaceholder}
        className="min-h-[180px] resize-none text-sm leading-relaxed"
      />

      <div className="flex items-center justify-between">
        <p className="text-xs text-muted-foreground">
          {inputMode === 'simple'
            ? 'The AI will generate the happy path first, then map assumptions.'
            : 'Describing the full path produces sharper, more specific assumptions.'}
        </p>
        <Button
          onClick={onSubmit}
          disabled={inputText.trim().length < 10}
        >
          {inputMode === 'simple' ? 'Map it →' : 'Generate assumptions →'}
        </Button>
      </div>
    </div>
  )
}

function LoadingState({ stage }: { stage: Stage }) {
  const messages: Record<string, string> = {
    'loading-happy-path': 'Mapping the happy path…',
    'loading-assumptions': 'Generating assumptions across all five dimensions…',
  }

  return (
    <div className="flex flex-col items-center justify-center py-20 gap-4">
      <div className="h-6 w-6 rounded-full border-2 border-border border-t-foreground animate-spin" />
      <p className="text-sm text-muted-foreground">{messages[stage] ?? 'Working…'}</p>
    </div>
  )
}

const ACTOR_COLORS: Record<string, string> = {
  User: 'border-blue-700 text-blue-300 bg-blue-950/40',
  Platform: 'border-neutral-700 text-neutral-300 bg-neutral-800/40',
  'Other User': 'border-emerald-700 text-emerald-300 bg-emerald-950/40',
  'Third-Party Service': 'border-purple-700 text-purple-300 bg-purple-950/40',
  Admin: 'border-amber-700 text-amber-300 bg-amber-950/40',
}

function ActorBadge({ actor }: { actor: string }) {
  const cls = ACTOR_COLORS[actor] ?? 'border-neutral-700 text-neutral-300 bg-neutral-800/40'
  return (
    <span className={`inline-flex items-center px-2 py-0.5 rounded text-[10px] font-medium border ${cls}`}>
      {actor}
    </span>
  )
}

function HappyPathReview({
  steps,
  onContinue,
  onReset,
}: {
  steps: HappyPathStep[]
  onContinue: () => void
  onReset: () => void
}) {
  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-base font-semibold text-foreground mb-1">Happy Path</h2>
        <p className="text-sm text-muted-foreground">
          Review the swim lanes. If something looks off, start over with a more detailed description.
        </p>
      </div>

      <div className="space-y-2">
        {steps.map((s, i) => (
          <div key={i} className="flex items-start gap-3 rounded-lg border border-neutral-800 px-4 py-3">
            <span className="text-xs text-neutral-600 font-mono mt-0.5 w-4 flex-shrink-0">{s.step}</span>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 mb-1">
                <ActorBadge actor={s.actor} />
              </div>
              <p className="text-sm text-neutral-300">{s.action}</p>
            </div>
          </div>
        ))}
      </div>

      <div className="flex items-center gap-3">
        <Button onClick={onContinue}>Generate assumption map →</Button>
        <button
          onClick={onReset}
          className="text-sm text-muted-foreground hover:text-foreground transition-colors"
        >
          Start over
        </button>
      </div>
    </div>
  )
}

function CompleteView({
  inputMode,
  inputText,
  happyPath,
  assumptions,
  onExport,
  onReset,
}: {
  inputMode: 'simple' | 'detailed'
  inputText: string
  happyPath: HappyPathStep[]
  assumptions: Assumption[]
  onExport: () => void
  onReset: () => void
}) {
  const [swimLanesOpen, setSwimLanesOpen] = useState(false)

  return (
    <div className="space-y-10">
      {/* Swim lanes — collapsed by default */}
      <section>
        <button
          onClick={() => setSwimLanesOpen(o => !o)}
          className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors mb-3"
        >
          <span className="text-xs">{swimLanesOpen ? '▼' : '▶'}</span>
          Happy Path
        </button>
        {swimLanesOpen && (
          <div className="space-y-2">
            {inputMode === 'simple' && happyPath.length > 0 ? (
              happyPath.map((s, i) => (
                <div key={i} className="flex items-start gap-3 rounded-lg border border-border bg-card px-4 py-3">
                  <span className="text-xs text-muted-foreground font-mono mt-0.5 w-4 flex-shrink-0">{s.step}</span>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <ActorBadge actor={s.actor} />
                    </div>
                    <p className="text-sm text-foreground">{s.action}</p>
                  </div>
                </div>
              ))
            ) : (
              <pre className="text-sm text-muted-foreground whitespace-pre-wrap font-mono leading-relaxed rounded-lg border border-border bg-card px-4 py-3">
                {inputText}
              </pre>
            )}
          </div>
        )}
      </section>

      {/* Priority Matrix */}
      <section>
        <h2 className="text-base font-semibold text-foreground mb-1">Priority Matrix</h2>
        <p className="text-xs text-muted-foreground mb-4">
          Top-right = high importance, low confidence — these need validation first.
          Hover any chip for the full assumption.
        </p>
        <PriorityMatrix assumptions={assumptions} />

        {/* Legend */}
        <div className="flex flex-wrap gap-3 mt-4">
          {DIMENSIONS.map(dim => {
            const c = DIMENSION_COLORS[dim]
            return (
              <div key={dim} className="flex items-center gap-1.5">
                <span className={`w-2 h-2 rounded-full inline-block`} style={{ backgroundColor: c.dot }} />
                <span className="text-xs text-muted-foreground">{dim}</span>
              </div>
            )
          })}
        </div>
      </section>

      {/* Assumption Map */}
      <section>
        <h2 className="text-base font-semibold text-foreground mb-4">Assumption Map</h2>
        <div className="space-y-6">
          {DIMENSIONS.map(dim => {
            const group = assumptions
              .filter(a => a.dimension === dim)
              .sort((a, b) => b.importance - a.importance)
            if (group.length === 0) return null
            const c = DIMENSION_COLORS[dim]
            return (
              <div key={dim}>
                <div className="flex items-center gap-2 mb-2">
                  <span className="w-2 h-2 rounded-full flex-shrink-0" style={{ backgroundColor: c.dot }} />
                  <h3 className="text-sm font-medium text-foreground">{dim}</h3>
                  <span className="text-xs text-muted-foreground">({group.length})</span>
                </div>
                <div className="space-y-1.5">
                  {group.map(a => (
                    <div
                      key={a.id}
                      className="flex items-start gap-3 rounded-lg border border-border bg-card px-4 py-2.5"
                    >
                      <p className="text-sm text-foreground flex-1 leading-relaxed">{a.text}</p>
                      <div className="flex items-center gap-3 flex-shrink-0 text-xs text-muted-foreground pt-0.5">
                        <span title="Importance">I:{a.importance}</span>
                        <span title="Confidence">C:{a.confidence}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )
          })}
        </div>
      </section>

      {/* Actions */}
      <section className="flex items-center gap-4 pb-10">
        <Button onClick={onExport} variant="outline">
          Export as Markdown
        </Button>
        <button
          onClick={onReset}
          className="text-sm text-muted-foreground hover:text-foreground transition-colors"
        >
          Start over
        </button>
      </section>
    </div>
  )
}

function PriorityMatrix({ assumptions }: { assumptions: Assumption[] }) {
  const [hovered, setHovered] = useState<string | null>(null)

  return (
    <div>
      <div className="flex gap-4">
        {/* Y-axis label */}
        <div className="flex items-center">
          <div
            className="text-[10px] text-muted-foreground whitespace-nowrap"
            style={{ writingMode: 'vertical-rl', transform: 'rotate(180deg)' }}
          >
            ↑ High Importance
          </div>
        </div>

        {/* Matrix */}
        <div className="flex-1 relative" style={{ paddingTop: '70%' }}>
          <div className="absolute inset-0 rounded-lg border border-border bg-card overflow-visible">
            {/* Top-right quadrant highlight */}
            <div className="absolute top-0 right-0 w-1/2 h-1/2 bg-amber-500/8 rounded-tr-lg" />

            {/* Center lines */}
            <div className="absolute top-1/2 left-0 right-0 h-px bg-border" />
            <div className="absolute left-1/2 top-0 bottom-0 w-px bg-border" />

            {/* Quadrant label */}
            <div className="absolute top-2 right-3 text-[9px] text-amber-500/50 font-semibold tracking-wider uppercase">
              Validate First
            </div>

            {/* Assumption chips */}
            {assumptions.map(a => {
              const xPct = (10 - a.confidence) / 9 * 88 + 6
              const yPct = (10 - a.importance) / 9 * 88 + 6
              const c = DIMENSION_COLORS[a.dimension]

              return (
                <div
                  key={a.id}
                  className="absolute"
                  style={{
                    left: `${xPct}%`,
                    top: `${yPct}%`,
                    transform: 'translate(-50%, -50%)',
                    zIndex: hovered === a.id ? 50 : 10,
                  }}
                  onMouseEnter={() => setHovered(a.id)}
                  onMouseLeave={() => setHovered(null)}
                >
                  <div
                    className={`px-1.5 py-0.5 rounded text-[9px] font-medium border cursor-default whitespace-nowrap ${c.bg} ${c.border} ${c.text}`}
                  >
                    {a.label}
                  </div>
                  {hovered === a.id && (
                    <div
                      className="absolute bottom-full left-1/2 -translate-x-1/2 mb-1.5 w-52 bg-card border border-border rounded-lg p-2.5 shadow-2xl pointer-events-none"
                      style={{ zIndex: 100 }}
                    >
                      <p className="text-[11px] text-foreground leading-relaxed mb-1">{a.text}</p>
                      <div className="flex items-center justify-between">
                        <span className={`text-[9px] font-medium ${c.text}`}>{a.dimension}</span>
                        <span className="text-[9px] text-muted-foreground">I:{a.importance} · C:{a.confidence}</span>
                      </div>
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        </div>
      </div>

      {/* X-axis labels */}
      <div className="flex justify-between text-[10px] text-muted-foreground mt-1.5 ml-7 pr-1">
        <span>← High Confidence</span>
        <span>Low Confidence →</span>
      </div>
    </div>
  )
}
